version: '3.4'

services:
  comms:
    image: ierturk/leap-dev
    build:
      context: .
      dockerfile: ./base.Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    network_mode: "host"
    # command: ["node", "--inspect=0.0.0.0:9229", "Source/server.js"]
    volumes:
      - ..:/usr/src/app
    working_dir: "/usr/src/app"
    # devices: 
    #   - /dev/ttyUSB0