version: '3.4'

services:
  base:
    image: ierturk/l4t-base:latest
    build:
      context: .
      dockerfile: l4t-base.Dockerfile
    runtime: nvidia
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash

  dev-base:
    image: ierturk/l4t-dev-base:latest
    build:
      context: .
      dockerfile: l4t-dev-base.Dockerfile
    runtime: nvidia
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash

  dev-ocv:
    image: ierturk/l4t-dev-ocv:latest
    build:
      context: .
      dockerfile: l4t-dev-ocv.Dockerfile
    runtime: nvidia
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash