version: '3.4'

services:
  l4t-dev:
    image: ierturk/l4t-dev
    build:
      context: .
      dockerfile: ./l4t-dev.Dockerfile
    # environment:
      # NODE_ENV: development
    # ports:
      # - 3000:3000cd ..
      # - 9229:9229
    network_mode: "host"
    # command: ["node", "--inspect=0.0.0.0:9229", "Source/server.js"]
    volumes:
      - ../zxing-cpp/:/workspaces
    working_dir: /workspaces
    # devices: 
    #   - /dev/ttyUSB0