version: '3.4'

services:
  base:
    image: ierturk/l4t-base:latest
    build:
      context: .
      dockerfile: l4t-base.Dockerfile
    # runtime: nvidia
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash

  dev-base:
    image: ierturk/l4t-dev-base:latest
    build:
      context: .
      dockerfile: l4t-dev-base.Dockerfile
    # runtime: nvidia
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash

  dev-libs:
    image: ierturk/l4t-dev-libs:latest
    build:
      context: .
      dockerfile: l4t-dev-libs.Dockerfile
    # runtime: nvidia
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash

  dev-work:
    image: ierturk/l4t-dev-work:latest
    build:
      context: .
      dockerfile: l4t-dev-work.Dockerfile
    # runtime: nvidia
    volumes:
      - type: bind
        source: ../..
        target: /workspace
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash

  work:
    image: ierturk/l4t-work:latest
    security_opt:
      - seccomp:unconfined
    shm_size: 256mb
    device_cgroup_rules:
      # ... for /dev/dri devices
      - 'c 226:* rmw'
    # runtime: nvidia
    environment:
      - WAYLAND_USER=ierturk
      - XDG_RUNTIME_DIR=/run/user/1000
      - WAYLAND_DISPLAY=wayland-0
      - DISPLAY=:0
      # - LIBGL_ALWAYS_INDIRECT=0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /run/user/1000
        target: /run/user/1000
      - type: bind
        source: /dev/video0
        target: /dev/video0
      - type: bind
        source: ../..
        target: /workspace
    network_mode: host
    privileged: true
    user: ierturk
    working_dir: /workspace
    command: /bin/bash
