version: '2.3'

services:
  weston:
    image: ierturk/l4t-weston:latest
    security_opt:
      - seccomp:unconfined
    shm_size: '256mb'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /run/user/1000
        target: /run/user/1000
      - type: bind
        source: ../..
        target: /workspace
      - type: bind
        source: ~/.ssh
        target: /home/ierturk/.ssh
        read_only: true
    cap_add:
      - CAP_SYS_TTY_CONFIG
      - SYS_PTRACE
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
      - 'c 81:* rmw'
      - 'c 199:* rmw'
    # command: --developer weston-launch --tty=/dev/tty7 --user=ierturk
    # command: weston-launch --tty=/dev/tty7 --user=ierturk
    # command: /bin/bash
    entrypoint: /usr/bin/entry.sh --developer weston-launch --tty=/dev/tty7 --user=ierturk
    # entrypoint: /bin/bash
    # entrypoint: /usr/lib/aarch64-linux-gnu/qt5/examples/wayland/pure-qml/pure-qml -platform eglfs
    runtime: nvidia
    network_mode: host
    privileged: true
    environment:
      - WAYLAND_USER=ierturk
      - XDG_RUNTIME_DIR=/run/user/1000
      - WAYLAND_DISPLAY=wayland-0
      - DISPLAY=:0
      - QT_QPA_PLATFORM=wayland
      - QT_IM_MODULE=qtvirtualkeyboard
      # - LIBGL_ALWAYS_INDIRECT=0
      # - QT_QPA_PLATFORM=eglfs
      # - QT_QPA_EGLFS_ALWAYS_SET_MODE=1
      # - QT_LOGGING_RULES=qt.qpa.*=true
      # - QT_LOGGING_RULES=qt.qpa.wayland.*=false
      - QT_QPA_EGLFS_INTEGRATION=eglfs_kms
      - QT_QPA_EGLFS_KMS_CONFIG=/workspace/kms.conf
      - QT_QPA_EGLFS_KMS_ATOMIC=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OPENBLAS_CORETYPE=ARMV8
      - IGNORE_X_LOCKS=1
    user: root
    working_dir: /workspace
    # healthcheck:
    #     test: ["CMD", "test", "-S", "/tmp/.X11-unix/X0"]
    #     interval: 5s
    #     timeout: 4s
    #     retries: 6
    #     start_period: 10s

  app:
    image: ierturk/l4t-app:latest
    security_opt:
      - seccomp:unconfined
    shm_size: '256mb'
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev/dri
        target: /dev/dri
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /run/user/1000
        target: /run/user/1000
      - type: bind
        source: ../..
        target: /workspace
      - type: bind
        source: ~/.ssh
        target: /home/ierturk/.ssh
        read_only: true
    cap_add:
      - CAP_SYS_TTY_CONFIG
      - SYS_PTRACE
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'
      - 'c 81:* rmw'
      - 'c 199:* rmw'
    entrypoint: /usr/sbin/sshd -p 2222 -D
    runtime: nvidia
    network_mode: host
    privileged: true
    environment:
      - WAYLAND_USER=ierturk
      - XDG_RUNTIME_DIR=/run/user/1000
      - WAYLAND_DISPLAY=wayland-0
      - DISPLAY=:0
      - QT_QPA_PLATFORM=wayland
      # - QT_IM_MODULE=qtvirtualkeyboard
      # - LIBGL_ALWAYS_INDIRECT=0
      # - QT_QPA_PLATFORM=eglf
      # - QT_QPA_EGLFS_ALWAYS_SET_MODE=1
      # - QT_LOGGING_RULES=qt.qpa.*=true
      # - QT_LOGGING_RULES=qt.qpa.wayland.*=false
      - QT_QPA_EGLFS_INTEGRATION=eglfs_kms
      - QT_QPA_EGLFS_KMS_CONFIG=/workspace/kms.conf
      - QT_QPA_EGLFS_KMS_ATOMIC=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - OPENBLAS_CORETYPE=ARMV8
    user: root
    working_dir: /workspace
    depends_on:
      - weston
