name: Publish Docker image Arch Linux cross-arm-none (bare metal) Development container

on:
  push:
    branches: master

jobs:
  main:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check Out Repo 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./arch/dev-cross-arm-none.Containerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ierturk/arch-dev-cross-arm-none:latest
          cache-from: type=registry,ref=ierturk/arch-dev-cross-arm-none:latest
          cache-to: type=inline
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
